spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&userSSL=false
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
